### ISSUE TITLE
data attributes

### ISSUE THREAD

**Issue by ndrwum** [animate-css/animate.css#1057]
It would make my life so much easier if we could include data attributes to html like the way wow.js implemented it. It would essentially look like this.
<section class="animate__animated animate__bounce" data-wow-duration="1s" data-wow-delay="1.3s"></section>

data-wow-duration: Change the animation duration
data-wow-delay: Delay before the animation starts

This would essentially save me from having to give different class names to every single uniquely animated html tag that I want to animate.

**Comment by eltonmesquita** [comment]
Hi,
I can't see the difference, in term of time-saving, adding classes or attributes. Besides, attribute selectors are more specific and are harder to overwrite. There is much more reasons why using classes, so I'm closing this as we won't implement it.

**Comment by ryanve** [comment]
FWIW I don't use `animate.css` but have sometimes favored data attributes for library design. Attribute selectors have equal specificity as classes. In JavaScript toggling attributes is sometimes easier than classes because you don't have to handle existing classes. However classes are standard and it's totally understandable to continue using classes here.
