### ISSUE TITLE
Removal of __animated prefix

### ISSUE THREAD

**Issue by MollyUrs** [animate-css/animate.css#1065]
**Is your feature request related to a problem? Not really a problem, just a suggestion :)

**Describe the solution you'd like** I personally prefer the old, shorter class names, I'm not sure if other people agree but now my elements have extremely long class names. e.g:

-  animate__animated animate__fadeInLeft animate__delay-2s animate__slower
VS
- animated fadeInLeft delay-2s slower

This is purely from a code-readability point of view.

**Describe alternatives you've considered** Removal of the animate__ prefix, possibly just a separate CDN link without the prefix

**Additional context** Thanks for the amazing work guys, I use animate.css in so many of my projects, its fantastic.

**Comment by eltonmesquita** [comment]
Hi, the prefix was added as a safety measure because it caused some issues - class clashing - on some projects. As a library of wide usage, we feel that this is a good choice. It's the best trade-off that we could provide right now.

Still, we provide the compact version, that you can read about in the [migration guide](https://animate.style/#migration) and a way to make your [own build](https://animate.style/#custom).

We feel that this is more than enough to please everyone and still provide a good library with best practices. embedded.

The final answer is, we will keep the prefix as this was a discussed and well-thought feature.

**Comment by MollyUrs** [comment]
Thanks for the response, I didn't see the compact version was available, thanks for pointing that out
