### ISSUE TITLE
Animations are jerky and too fast on macOS Big Sur Safari

### ISSUE THREAD

**Issue by benjam23** [animate-css/animate.css#1097]
Animations are jerky and too fast on macOS Big Sur 11.0 Beta (20A5354i) & Safari - Version 14.0 (16610.1.25.1.3).
[Screen Recording 2020-08-30 at 07.21.46.mov.zip](https://github.com/animate-css/animate.css/files/5146410/Screen.Recording.2020-08-30.at.07.21.46.mov.zip)

**Comment by WarenGonzaga** [comment]
Thank you for reporting @benjam23 we really appreciate it, I checked your video and I find it funny because it animates in weird way. I don't know if is something with your browser or some of our implementation for the "prefer-reduced-motion" kindly check our discussion regarding this on issue #914 and this PR #1043

**Comment by WarenGonzaga** [comment]
Also, tagging @eltonmesquita and @daneden for the issue I don't have macOS or safari browser can't debug it at the moment.

**Comment by daneden** [comment]
Thanks for reporting, @benjam23! Since you’re seeing this on a beta version of macOS/Safari, I’m going to close this issue and chalk it up to beta bugs. For what it’s worth, I see the same problem you’re seeing, but on closer inspection it’s pretty surprising. When you observe the animation in web inspector, you can see that its frame animates at the correct speed, but the rendered result is sped up! Super interesting bug indeed, worth filing a radar for Apple to investigate. Added a screen recording too.

[Screen Recording 2020-08-30 at 12.26.13.zip](https://github.com/animate-css/animate.css/files/5146715/Screen.Recording.2020-08-30.at.12.26.13.zip)
