### ISSUE TITLE
Animate when element appears in viewport

### ISSUE THREAD

**Issue by fuzenco** [animate-css/animate.css#1119]
I’d love to see an **easy** way to animate elements when they appear within a viewport. An added bonus would be exit animations (based on an element moving out of the viewport). Maybe a class added to the body tag could denote when want Animate CSS to operate within-viewport versus on page load.

**Comment by WarenGonzaga** [comment]
@fuzenco do you have example of it? So I can take a look and may be I can add it as a feature. Looking forward to your response.

**Comment by sthiepaan** [comment]
Hello @fuzenco 👋,
as I understand your request, the thing that you want to achieve is not possible using _CSS_ only.
Also, since _animate.css_ is pure _CSS_ library it doesn't make sense to extend it to have feature like this.

@WarenGonzaga please correct me if I'm wrong at any point 😉

To solve your problem, what you actually need is _JavaScript_ and [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).
You can write it on your own or try [_io-Animate_](https://www.npmjs.com/package/io-animate) NPM Package (don't know if it works, never used it tho)

**Comment by WarenGonzaga** [comment]
> Hello @fuzenco 👋,
> as I understand your request, the thing that you want to achieve is not possible using _CSS_ only.
> Also, since _animate.css_ is pure _CSS_ library it doesn't make sense to extend it to have feature like this.
> 
> @WarenGonzaga please correct me if I'm wrong at any point 😉
> 
> To solve your problem, what you actually need is _JavaScript_ and [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).
> You can write it on your own or try [_io-Animate_](https://www.npmjs.com/package/io-animate) NPM Package (don't know if it works, never used it tho)

Oh... we should acknowledge this io-Animate and make it official on our next project... currently we are working on another version of animate.css which is more powerful and this idea would be good to add. Let's discuss this @eltonmesquita 

You have point! Let's see the issue on a demo so we can confirm it and fix it.

**Comment by eltonmesquita** [comment]
I think this is solved as Animate.css won't support this as we aim to keep this library **css** only. Right now I prefer to not make any external library official (any library outside of this organization).

**Comment by WarenGonzaga** [comment]
@eltonmesquita Indeed as we are working on other version of animation.

**Comment by fuzenco** [comment]
I’d not seen my notifications earlier, so sorry for not replying. Understood on the reason why.

**Comment by kazemimorteza68** [comment]
we can use below js code 

`
    const element = document.querySelector('#product_image');
    const observer = new IntersectionObserver(entries => {
        element.classList.toggle('animate__pulse', entries[0].isIntersecting );
    });

    observer.observe( element );

`
