### ISSUE TITLE
Animations are too fast on MacOs Catalina

### ISSUE THREAD

**Issue by rodrigo-fonseca** [animate-css/animate.css#1123]
The "problem" start when I updated my macOs, after that, the animation are clearly faster than usual, too fast I would say

***
Desktop
- OS: macOS Catalina (10.15.6)
- Browser Safari
- Version 14.0

iPhone 7

- OS: 14.0.1

**Comment by eltonmesquita** [comment]
Hi. I have the same versions as you and everything's working fine. Maybe this is something localized?

**Comment by rodrigo-fonseca** [comment]
> Hi. I have the same versions as you and everything's working fine. Maybe this is something localized?

Maybe :( I really don't know, I'm using it with my Ionic 4.x application and definitely, after I updated my iPhone, all the animations are faster and less smooth

**Comment by WarenGonzaga** [comment]
This issue is known and @daneden is currently coordinating with the MacOs team... that's what I know... 
To learn more read this PR #1097

**Comment by eltonmesquita** [comment]
Thanks for the reporting, but I'm closing this as there isn't much we can do about it. Safari bugs are usually weird and very specific. Most of the times the fix is some nasty browser sniffing technique target some specific Safari's versions.

Unfortunately, the far we can go is to file a bug on its tracker.
