### ISSUE TITLE
iOS 14 - Animation speed issue

### ISSUE THREAD

**Issue by asangadev** [animate-css/animate.css#1143]
Hi there, any idea why the animations are bit faster on iOS 14 Safari? 

Is this something to do with iOS 14 Safari engine?

**Comment by eltonmesquita** [comment]
Sorry for the late answer.

Yeah, this is a weird random issue with this new Safari release. See #1123 and #1097.
There is no fix right now and I'd advise to not try to fix it as it'll probably break the animations for all the rest of your userbase. Even browser sniffing techniques would probably fail because not every Safari 14 shows this behaviour.

The best we can do right now is to hope for Apple to fix this in a future release.

**Comment by asangadev** [comment]
All good! Thanks for the update. Will wait then.

**Comment by asangadev** [comment]
This is fixed in iOS 14.3
