### ISSUE TITLE
Two animations on page open.

### ISSUE THREAD

**Issue by kkaiser1952** [animate-css/animate.css#1196]
I'm doing this in a function but the second animation never happens. 

const element = document.querySelector('#pgtitle2');
            element.classList.add('animate__animated', 'animate__slideInRight');
const element2 = document.querySelector('#rightCorner');
            element2.classList.add('animate__animated', 'animate__slideInLeft');

Any idea why?

**Comment by WarenGonzaga** [comment]
Hi @kkaiser1952, do you have any [codepen](https://codepen.io/) link for that?

This might be the problem on how you markup your element.

**Comment by tirlochanarora16** [comment]
Might be some mistake in the `id` name.

**Comment by kkaiser1952** [comment]
I don't have code pen set up, I'll go do that.

**Comment by eltonmesquita** [comment]
Any news @kkaiser1952?

**Comment by kkaiser1952** [comment]
I don't have a solution and not sure how to set up an example in codepen, I'll revisit this when I can and learn how to leave an example.

**Comment by eltonmesquita** [comment]
Your issue is that you're not waiting for the first animation to finish before adding the second one. Use the [function on our docs to do this](https://animate.style/#javascript). 

[Codepen](https://codepen.io/trending) and [Codesandbox](https://codesandbox.io/) are free and easy-to-use services, just create an account and follow the instructions to create a new and shareable environment. But anyway, just follow the instructions on our docs and you should get your problem solved.
