### ISSUE TITLE
Hover events cause onload animations to replay. 

### ISSUE THREAD

**Issue by FxllenCode** [animate-css/animate.css#1260]
**Describe the bug**

I'm seeing some weird behavior when using the main class provided by CDN in the documentation. It happens after using a custom CSS class on a `:hover` event. Here is what is looks like:

![t9ErSmKybA](https://user-images.githubusercontent.com/40151425/113802720-32670e00-9729-11eb-8d94-045afdaf9029.gif)

It correctly fades in onload, but then it fades in again after the hover event is called. 

**To Reproduce** Steps to reproduce the behavior:

1. Add the `animate__animated animate__fadeIn` classes to an element. 
2. On the same element add another animation event binded to a `:hover` event. 
3. When hovering is complete, it replays the animation. This isn't intended AFAIK. 

**Expected behavior**

It only plays the original animation on load, and does not replay it after a hover event. 

**Thanks!**

**Comment by eltonmesquita** [comment]
It's very hard to figure anything out without a live version. Can you please provide a reduced case on codepen or any other platform for we can try to debug the issue?

**Comment by FxllenCode** [comment]
@eltonmesquita 

I can provide a public repo if that works?

**Comment by FxllenCode** [comment]
Hey @eltonmesquita,

Here's a pen that clearly shows the issue. Just hover over one of the cards and notice that `onload` fires right after:

https://codepen.io/FxllenCode/pen/ExZdORz

**Comment by eltonmesquita** [comment]
This is just how CSS works, every time a hover event happens it starts the animation (wobble) because you're overriding the previous value (zoomIn). When it fires the hover-out event the first declaration (zoomIn) will override the second one (wobble). It's not an issue nor a bug with the library or CSS it's just the intended CSS behaviour. 

To work around this just wrap the `<li/>` content in a `<div/>` and add the hover animation to it and keep the initial animation in the `<li/>`. You'll probably have to mess around a bit with your html/css but it's up to you to figure this part out 😄 

I'm closing this as it's actually unrelated to the library.
